/**
 * Text for the public landing page (src/pages/Landing.tsx).
 * Kept apart from i18n.tsx so the marketing copy can change without touching app strings.
 * Both objects must have the same keys (the Urdu one is type-checked against English).
 */

export const landingEn = {
  skip: 'Skip to content',
  navFeatures: 'Features',
  navHow: 'How it works',
  navFaq: 'FAQ',
  menuLabel: 'Main',

  heroEyebrow: 'For pesticide, fertilizer and seed shops',
  trust1: '60-day expiry alerts',
  trust2: 'English & اردو',
  trust3: 'Works on mobile',
  trust4: 'Excel import',
  heroAlt: 'Agri Inventory dashboard in dark mode with expiry alerts and quick buttons for Stock In, New Sale, Khata and Reports',

  featuresKicker: 'Features',
  featuresTitle: 'Everything your shop counter needs',
  featuresText: 'From the day stock arrives to the day it is sold, every bottle, gallon and bag is tracked by batch and expiry.',

  f1Eyebrow: 'Expiry and batches',
  f1Title: 'Know what expires, before it expires',
  f1Text: 'Every stock in records the batch number, manufacturing date and expiry date. Items expiring within 60 days are shown at the top of every screen, so nothing is forgotten on the shelf.',
  f1b1: 'Batch, mfg and expiry saved with each purchase',
  f1b2: 'Alert strip on every screen, 60 days in advance',
  f1b3: 'Expiry report for the whole shop',
  f1Alt: 'Stock In screen with supplier, batch number, manufacturing date, expiry date, quantity and purchase rate',

  f2Eyebrow: 'Sales and receipts',
  f2Title: 'Fast sales with printed receipts',
  f2Text: 'Search a product, enter the quantity and save. Older batches go out first automatically, and the receipt is ready to print on a thermal printer or A4 paper.',
  f2b1: 'Older batches sold first (FEFO), automatically',
  f2b2: 'Discount, amount received and credit to khata',
  f2b3: '80 mm thermal or A4 receipt, and returns against an invoice',
  f2Alt: 'New Sale screen with customer, product search, discount, total, amount received and balance to khata',

  f3Eyebrow: 'Khata and Roznamcha',
  f3Title: 'Your khata and roznamcha, kept for you',
  f3Text: 'Customer and supplier ledgers work like a khata book, and credit sales are added to the khata automatically. The roznamcha shows every rupee that came in or went out, day by day.',
  f3b1: 'Customer and supplier khata with running balance',
  f3b2: 'Credit sales and purchases posted automatically',
  f3b3: 'Daily cash book with party, details and payments',
  f3Alt: 'Roznamcha (daily cash book) table with type, party, detail and cash out columns',

  f4Eyebrow: 'Reports and profit',
  f4Title: 'Clear reports, any day you want',
  f4Text: 'See opening, in, out and closing stock for any day or month. Check sales and profit, then export to Excel or print with one click.',
  f4b1: 'Daily, monthly and day by day stock reports',
  f4b2: 'Stock on any date, sales and profit',
  f4b3: 'Export to Excel or print',
  f4Alt: 'Daily stock report with opening, in, out, adjust and closing stock for each product and pack size',

  moreKicker: 'And much more',
  moreTitle: 'Small details that save time every day',
  filtersTitle: 'Smart filters',
  filtersText: 'Find products in stock, low, out of stock or expiring in one tap. Filter by category and company.',
  filtersAlt: 'Products list with the filters panel open showing in stock, low stock, out of stock and expiring',
  importTitle: 'Bulk stock in from Excel or CSV',
  importText: 'Download a template already filled with your products, enter quantities and dates, and upload it.',
  importAlt: 'Bulk stock in screen with template download and an area to upload an Excel or CSV file',
  g1Title: 'Every pack size',
  g1Text: 'From 200 ml bottles to 15 L gallons, packets and bags.',
  g2Title: 'Sell bags loose by kg',
  g2Text: 'Open a bag and sell part of it by weight.',
  g3Title: 'Urdu & English',
  g3Text: 'Switch any time. Urdu reads right to left.',
  g4Title: 'Phone and computer',
  g4Text: 'Works in the browser. Nothing to install.',
  g5Title: 'Dark mode',
  g5Text: 'Easy on the eyes in the evening.',
  g6Title: 'Staff logins with roles',
  g6Text: 'Owner, admin and staff, each with their own login.',
  g7Title: 'Fix mistakes safely',
  g7Text: 'Edit or delete a wrong entry and stock updates itself.',
  g8Title: 'Full stock history',
  g8Text: 'Every entry shows the date and who made it.',

  urduKicker: 'Built for Pakistan',
  urduTitle: 'Built for Urdu and for mobile',
  urduText: 'Your staff can use the app in the language they are comfortable with. The whole app switches to Urdu and reads right to left, and it fits a phone screen as well as a computer.',
  urduB1: 'One tap to switch between English and اردو',
  urduB2: 'Urdu names for products and categories',
  urduB3: 'Bottom menu on phones for Stock In, New Sale and Khata',
  urduAlt: 'Daily stock report in Urdu with the sidebar on the right',
  mobileAlt: 'Agri Inventory reports screen on a mobile phone with a bottom menu',

  howKicker: 'How it works',
  howTitle: 'Start in three simple steps',
  s1Title: 'Create your shop',
  s1Text: 'Sign up, name your shop and invite your staff with a code.',
  s2Title: 'Add products and stock',
  s2Text: 'Add products one by one, or import your full list from Excel.',
  s3Title: 'Start selling',
  s3Text: 'Make sales, print receipts and see your reports every day.',

  faqKicker: 'FAQ',
  faqTitle: 'Common questions',
  q1: 'Does it need internet?',
  a1: 'Yes. Agri Inventory is an online web app. Your data is saved in the cloud, so you can open your shop from any phone or computer and see the same stock.',
  q2: 'Is my data safe and private?',
  a2: 'Each shop’s data is kept separate. Only the members of your shop can see it, and everyone signs in with their own account.',
  q3: 'Can my staff use it?',
  a3: 'Yes. Create an invite code and send it to your staff. Each person gets their own login with a role: owner, admin or staff. Only the owner and admins can edit or delete entries.',
  q4: 'Does it work in Urdu?',
  a4: 'Yes. Switch between English and اردو with one tap. The whole app turns right to left in Urdu, and you can save Urdu names for your products.',
  q5: 'Can I import my existing product list?',
  a5: 'Yes. On Bulk stock in, download an Excel or CSV template that is already filled with your products, enter the quantities, batch and expiry dates, and upload it.',
  q6: 'Does it work on mobile?',
  a6: 'Yes. It runs in the browser on Android phones, iPhones, tablets and computers. On a phone it shows a simple bottom menu for the screens you use most.',
  q7: 'Can I print receipts and reports?',
  a7: 'Yes. Print sale receipts on an 80 mm thermal printer or on A4 paper. Reports can be printed or exported to Excel.',

  ctaTitle: 'Ready to bring your shop online?',
  ctaText: 'Create your shop in a few minutes and start tracking stock, expiry and khata today.',
  whatsapp: 'Chat on WhatsApp',
  whatsappFloat: 'Contact us on WhatsApp',
  waGreeting: 'Assalam o Alaikum! I would like to know more about Agri Inventory.',

  footerText: 'Inventory, sales and khata for agricultural pesticide, fertilizer and seed shops.',
  rights: 'All rights reserved.',
  contact: 'Contact',
}

export type LandingKey = keyof typeof landingEn

export const landingUr: Record<LandingKey, string> = {
  skip: 'مواد پر جائیں',
  navFeatures: 'خصوصیات',
  navHow: 'طریقہ کار',
  navFaq: 'سوالات',
  menuLabel: 'مینو',

  heroEyebrow: 'زرعی ادویات، کھاد اور بیج کی دکانوں کے لیے',
  trust1: 'ایکسپائری سے 60 دن پہلے الرٹ',
  trust2: 'English اور اردو',
  trust3: 'موبائل پر بھی چلے',
  trust4: 'ایکسل سے امپورٹ',
  heroAlt: 'ڈارک موڈ میں زرعی انوینٹری کا ڈیش بورڈ، ایکسپائری الرٹ اور اسٹاک آمد، نئی فروخت، کھاتہ اور رپورٹس کے بٹن',

  featuresKicker: 'خصوصیات',
  featuresTitle: 'دکان کے کاؤنٹر کی ہر ضرورت',
  featuresText: 'مال آنے سے لے کر فروخت ہونے تک، ہر بوتل، گیلن اور بیگ کا بیچ اور ایکسپائری کے ساتھ ریکارڈ۔',

  f1Eyebrow: 'ایکسپائری اور بیچ',
  f1Title: 'ایکسپائر ہونے سے پہلے ہی پتا چل جائے',
  f1Text: 'ہر اسٹاک آمد پر بیچ نمبر، تاریخ تیاری اور ایکسپائری کی تاریخ محفوظ ہوتی ہے۔ 60 دن میں ایکسپائر ہونے والا مال ہر اسکرین کے اوپر نظر آتا ہے، تاکہ شیلف پر کچھ بھی نہ بھولے۔',
  f1b1: 'ہر خریداری کے ساتھ بیچ، تاریخ تیاری اور ایکسپائری',
  f1b2: 'ہر اسکرین پر 60 دن پہلے الرٹ',
  f1b3: 'پوری دکان کی ایکسپائری رپورٹ',
  f1Alt: 'اسٹاک آمد کی اسکرین جس میں سپلائر، بیچ نمبر، تاریخ تیاری، ایکسپائری، تعداد اور خرید ریٹ ہے',

  f2Eyebrow: 'فروخت اور رسید',
  f2Title: 'تیز فروخت اور پرنٹ شدہ رسید',
  f2Text: 'چیز تلاش کریں، تعداد لکھیں اور محفوظ کریں۔ پرانا بیچ خود بخود پہلے نکلتا ہے، اور رسید تھرمل پرنٹر یا A4 کاغذ پر پرنٹ کے لیے تیار ہوتی ہے۔',
  f2b1: 'پرانا بیچ خود بخود پہلے فروخت (FEFO)',
  f2b2: 'رعایت، وصول شدہ رقم اور باقی کھاتے میں',
  f2b3: '80 ملی میٹر تھرمل یا A4 رسید، اور بل کے حساب سے واپسی',
  f2Alt: 'نئی فروخت کی اسکرین جس میں گاہک، چیز کی تلاش، رعایت، کل رقم، وصول شدہ رقم اور کھاتے کا بقایا ہے',

  f3Eyebrow: 'کھاتہ اور روزنامچہ',
  f3Title: 'آپ کا کھاتہ اور روزنامچہ، خود بخود تیار',
  f3Text: 'گاہکوں اور سپلائرز کے کھاتے کھاتہ بک کی طرح چلتے ہیں، اور ادھار فروخت خود بخود کھاتے میں چلی جاتی ہے۔ روزنامچہ میں روز کا ہر آنے اور جانے والا روپیہ نظر آتا ہے۔',
  f3b1: 'گاہک اور سپلائر کا کھاتہ، بقایا کے ساتھ',
  f3b2: 'ادھار فروخت اور خریداری خود بخود درج',
  f3b3: 'روزانہ کیش بک، پارٹی، تفصیل اور ادائیگیوں کے ساتھ',
  f3Alt: 'روزنامچہ کی جدول جس میں قسم، پارٹی، تفصیل اور نقد ادائیگی کے کالم ہیں',

  f4Eyebrow: 'رپورٹس اور منافع',
  f4Title: 'واضح رپورٹس، جس دن کی چاہیں',
  f4Text: 'کسی بھی دن یا مہینے کا ابتدائی، آمد، روانگی اور اختتامی اسٹاک دیکھیں۔ فروخت اور منافع چیک کریں، پھر ایک کلک میں ایکسل میں نکالیں یا پرنٹ کریں۔',
  f4b1: 'روزانہ، ماہانہ اور دن بہ دن اسٹاک رپورٹ',
  f4b2: 'کسی بھی تاریخ کا اسٹاک، فروخت اور منافع',
  f4b3: 'ایکسل میں ایکسپورٹ یا پرنٹ',
  f4Alt: 'روزانہ اسٹاک رپورٹ جس میں ہر چیز اور پیک سائز کا ابتدائی، آمد، روانگی، درستگی اور اختتامی اسٹاک ہے',

  moreKicker: 'اور بھی بہت کچھ',
  moreTitle: 'چھوٹی سہولتیں جو روز وقت بچاتی ہیں',
  filtersTitle: 'آسان فلٹر',
  filtersText: 'دستیاب، کم، ختم یا ایکسپائر ہونے والی چیزیں ایک ٹیپ میں دیکھیں۔ کیٹیگری اور کمپنی سے فلٹر کریں۔',
  filtersAlt: 'اشیاء کی فہرست جس میں فلٹر کھلا ہے: دستیاب، کم اسٹاک، ختم اور ایکسپائر ہونے والی',
  importTitle: 'ایکسل یا CSV سے اکٹھا اسٹاک',
  importText: 'اپنی اشیاء سے بھرا ہوا ٹیمپلیٹ ڈاؤن لوڈ کریں، تعداد اور تاریخیں لکھیں اور اپ لوڈ کر دیں۔',
  importAlt: 'اکٹھا اسٹاک آمد کی اسکرین جس میں ٹیمپلیٹ ڈاؤن لوڈ اور ایکسل یا CSV فائل اپ لوڈ کرنے کی جگہ ہے',
  g1Title: 'ہر پیک سائز',
  g1Text: '200 ملی لیٹر بوتل سے 15 لیٹر گیلن، پیکٹ اور بیگ تک۔',
  g2Title: 'بیگ کھول کر کلو میں فروخت',
  g2Text: 'بیگ کھولیں اور وزن کے حساب سے کھلا بیچیں۔',
  g3Title: 'اردو اور English',
  g3Text: 'جب چاہیں بدلیں۔ اردو دائیں سے بائیں چلتی ہے۔',
  g4Title: 'موبائل اور کمپیوٹر',
  g4Text: 'براؤزر میں چلتا ہے۔ کچھ انسٹال نہیں کرنا۔',
  g5Title: 'ڈارک موڈ',
  g5Text: 'شام کے وقت آنکھوں کو آرام۔',
  g6Title: 'عملے کے الگ لاگ اِن',
  g6Text: 'مالک، ایڈمن اور اسٹاف، ہر ایک کا اپنا لاگ اِن۔',
  g7Title: 'غلطی آسانی سے درست کریں',
  g7Text: 'غلط اندراج میں ترمیم کریں یا حذف کریں، اسٹاک خود ٹھیک ہو جاتا ہے۔',
  g8Title: 'اسٹاک کا مکمل ریکارڈ',
  g8Text: 'ہر اندراج پر تاریخ اور کرنے والے کا نام۔',

  urduKicker: 'پاکستان کے لیے تیار',
  urduTitle: 'اردو اور موبائل کے لیے بنایا گیا',
  urduText: 'آپ کا عملہ اپنی پسند کی زبان میں کام کر سکتا ہے۔ پوری ایپ اردو میں دائیں سے بائیں چلتی ہے، اور موبائل اور کمپیوٹر دونوں پر آسانی سے استعمال ہوتی ہے۔',
  urduB1: 'ایک ٹیپ میں English اور اردو',
  urduB2: 'اشیاء اور کیٹیگری کے اردو نام',
  urduB3: 'موبائل پر نیچے مینو: اسٹاک آمد، نئی فروخت اور کھاتہ',
  urduAlt: 'اردو میں روزانہ اسٹاک رپورٹ، سائیڈ بار دائیں جانب',
  mobileAlt: 'موبائل فون پر زرعی انوینٹری کی رپورٹس اسکرین اور نیچے مینو',

  howKicker: 'طریقہ کار',
  howTitle: 'تین آسان مرحلوں میں شروع کریں',
  s1Title: 'اپنی دکان بنائیں',
  s1Text: 'سائن اپ کریں، دکان کا نام لکھیں اور کوڈ سے عملے کو شامل کریں۔',
  s2Title: 'اشیاء اور اسٹاک شامل کریں',
  s2Text: 'ایک ایک کر کے اشیاء شامل کریں، یا پوری فہرست ایکسل سے امپورٹ کریں۔',
  s3Title: 'فروخت شروع کریں',
  s3Text: 'فروخت کریں، رسید پرنٹ کریں اور روز اپنی رپورٹس دیکھیں۔',

  faqKicker: 'سوالات',
  faqTitle: 'عام سوالات',
  q1: 'کیا انٹرنیٹ ضروری ہے؟',
  a1: 'جی ہاں۔ زرعی انوینٹری ایک آن لائن ویب ایپ ہے۔ آپ کا ڈیٹا کلاؤڈ پر محفوظ ہوتا ہے، اس لیے آپ کسی بھی موبائل یا کمپیوٹر سے اپنی دکان کھول کر وہی اسٹاک دیکھ سکتے ہیں۔',
  q2: 'کیا میرا ڈیٹا محفوظ اور نجی ہے؟',
  a2: 'ہر دکان کا ڈیٹا الگ رکھا جاتا ہے۔ اسے صرف آپ کی دکان کے ممبر دیکھ سکتے ہیں، اور ہر شخص اپنے اکاؤنٹ سے لاگ اِن کرتا ہے۔',
  q3: 'کیا میرا عملہ اسے استعمال کر سکتا ہے؟',
  a3: 'جی ہاں۔ دعوتی کوڈ بنائیں اور عملے کو بھیج دیں۔ ہر شخص کا اپنا لاگ اِن ہوتا ہے اور کردار ہوتا ہے: مالک، ایڈمن یا اسٹاف۔ اندراج میں ترمیم یا حذف صرف مالک اور ایڈمن کر سکتے ہیں۔',
  q4: 'کیا یہ اردو میں چلتی ہے؟',
  a4: 'جی ہاں۔ ایک ٹیپ میں English اور اردو کے درمیان بدلیں۔ اردو میں پوری ایپ دائیں سے بائیں ہو جاتی ہے، اور آپ اپنی اشیاء کے اردو نام بھی محفوظ کر سکتے ہیں۔',
  q5: 'کیا میں اپنی موجودہ اشیاء کی فہرست امپورٹ کر سکتا ہوں؟',
  a5: 'جی ہاں۔ اکٹھا اسٹاک آمد میں ایکسل یا CSV ٹیمپلیٹ ڈاؤن لوڈ کریں جو پہلے سے آپ کی اشیاء سے بھرا ہوتا ہے، تعداد، بیچ اور ایکسپائری لکھیں اور اپ لوڈ کر دیں۔',
  q6: 'کیا یہ موبائل پر چلتی ہے؟',
  a6: 'جی ہاں۔ یہ اینڈرائیڈ فون، آئی فون، ٹیبلٹ اور کمپیوٹر کے براؤزر میں چلتی ہے۔ موبائل پر سب سے زیادہ استعمال ہونے والی اسکرینوں کے لیے نیچے آسان مینو ہوتا ہے۔',
  q7: 'کیا میں رسید اور رپورٹس پرنٹ کر سکتا ہوں؟',
  a7: 'جی ہاں۔ فروخت کی رسید 80 ملی میٹر تھرمل پرنٹر یا A4 کاغذ پر پرنٹ کریں۔ رپورٹس پرنٹ بھی ہو سکتی ہیں اور ایکسل میں بھی نکل سکتی ہیں۔',

  ctaTitle: 'اپنی دکان آن لائن لانے کے لیے تیار ہیں؟',
  ctaText: 'چند منٹ میں اپنی دکان بنائیں اور آج ہی اسٹاک، ایکسپائری اور کھاتے کا حساب شروع کریں۔',
  whatsapp: 'واٹس ایپ پر بات کریں',
  whatsappFloat: 'واٹس ایپ پر رابطہ کریں',
  waGreeting: 'السلام علیکم! مجھے زرعی انوینٹری کے بارے میں مزید معلومات چاہییں۔',

  footerText: 'زرعی ادویات، کھاد اور بیج کی دکانوں کے لیے اسٹاک، فروخت اور کھاتہ۔',
  rights: 'جملہ حقوق محفوظ ہیں۔',
  contact: 'رابطہ',
}
